In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [ ]:
text = """
Mutation is the sudden heritable change that occurred in an organism. It may be
caused by spontaneous or through artificial induction and the resulted mutant shows
change in the gene or chromosomes. Induced mutagenesis techniques have
successfully produced and commercialized quite a large number of new promising
varieties in different crops worldwide, including ornamental plants. Induced
mutagenesis has been most successful in ornamental crops. The improvement
achieved through mutation breeding in ornamental crops includes compact growth,
attractive variegated leaves and novel flower colour and shapes. Ornamental plants
with a rich variety of flower colors and shapes are highly prized, and the production of
mutant cultivars that differ in these traits is in demand because all other growth habits
are identical. Many species of ornamental plants, such as chrysanthemum
(Chrysanthemum spp.), rose (Rosa spp.), and carnation (Dianthus caryophyllus), are
vegetatively propagated, making it relatively easy to propagate mutants. This review
not only provides examples of successful mutation breeding results using physical and
chemical mutagens, but it also describes research on mutagenesis and compares results
of gamma ray, EMS and DES using ornamental plants.
"""

In [ ]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts([text])

total_words = len(tokenizer.word_index) + 1

print("Total vocabulary:", total_words)

Total vocabulary: 124


In [ ]:
input_sequences = []

for line in text.split("\n"):

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):

        n_gram = token_list[:i+1]

        input_sequences.append(n_gram)

print(input_sequences[:5])

[[7, 12], [7, 12, 5], [7, 12, 5, 29], [7, 12, 5, 29, 30], [7, 12, 5, 29, 30, 13]]


In [ ]:
max_sequence_len = max([len(x) for x in input_sequences])

input_sequences = pad_sequences(
    input_sequences,
    maxlen=max_sequence_len,
    padding='pre'
)

print(input_sequences[:5])

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  7 12]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  7 12  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7 12  5 29]
 [ 0  0  0  0  0  0  0  0  0  0  0  7 12  5 29 30]
 [ 0  0  0  0  0  0  0  0  0  0  7 12  5 29 30 13]]


In [ ]:
X = input_sequences[:,:-1]

y = input_sequences[:,-1]

y = tf.keras.utils.to_categorical(y, num_classes=total_words)

In [ ]:
model = Sequential()

model.add(Embedding(total_words, 16, input_length=max_sequence_len-1))

model.add(SimpleRNN(64))

model.add(Dense(total_words, activation='softmax'))

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_6 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0120 - loss: 4.8283   
Epoch 2/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0241 - loss: 4.7945
Epoch 3/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0361 - loss: 4.7716    
Epoch 4/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0422 - loss: 4.7432    
Epoch 5/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0663 - loss: 4.6922    
Epoch 6/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0723 - loss: 4.6465
Epoch 7/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0663 - loss: 4.6051
Epoch 8/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0783 - loss: 4.5457
Epoch 9/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0843 - loss: 4.5013
Epoch 10/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0904 - loss: 4.4533
Epoch 11/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0843 - loss: 4.3855
Epoch 12/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accura

In [ ]:
seed_text = "aswathy"

next_words = 20

for _ in range(next_words):

    token_list = tokenizer.texts_to_sequences([seed_text])[0]

    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len-1,
        padding='pre'
    )

    predicted = np.argmax(model.predict(token_list), axis=-1)

    for word, index in tokenizer.word_index.items():
        if index == predicted:
            seed_text += " " + word

print(seed_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
aswathy is is making it relatively easy to propagate mutants this review through artificial new and the plants such as chrysanthemum
