#Recurrent Neural Network


- A Recurrent Neural Network (RNN) is a type of artificial neural network designed to process sequential data.

- Unlike traditional neural networks, RNNs have a memory mechanism that allows them to use information from previous inputs.

- This makes RNNs suitable for tasks where order and context matter, such as language and time series.

Examples of sequential data:

- text sentences

- speech signals

- stock market data

- video frames

##Why RNN is Needed

- Traditional neural networks process inputs independently, meaning they do not remember previous information.


Example sentence:

- I grew up in Kerala. I love its culture.

- To understand the word "its", the model must remember Kerala.

- RNNs solve this problem by maintaining a hidden state that stores past information.

###Basic Idea of RNN

An RNN processes inputs one step at a time while maintaining a hidden state.

Example sentence:

    I love artificial intelligence

Processing sequence:

    I → love → artificial → intelligence

At each step, the model updates its memory.

### RNN Architecture

The basic structure of an RNN includes:

- Input layer

- Hidden layer (memory state)

- Output layer

    Input → Hidden State → Output
            ↑
            Memory from previous step

###Hidden State

The hidden state acts as the memory of the network.

At each time step:

    h_t = f(Wx_t + Uh_{t-1})


| Term    | Meaning               |
| ------- | --------------------- |
| h_t     | current hidden state  |
| x_t     | current input         |
| h_{t-1} | previous hidden state |
| W,U     | weight matrices       |
| f       | activation function   |


### Types of RNN Architectures

Different RNN architectures are used depending on the task.

1. One-to-One

        Single input → single output.

    Example:

        Image classification.

2. One-to-Many

        Single input → sequence output.

      Example:

        Image captioning.

3. Many-to-One

        Sequence input → single output.

      Example:

        Sentiment analysis.

        This movie was amazing

        Output: Positive

4. Many-to-Many

        Sequence input → sequence output.

      Example:

        Machine translation.

        English → French

### Example of RNN in NLP

Sentence:

    The movie was fantastic



| Step | Input     | Hidden State |
| ---- | --------- | ------------ |
| 1    | The       | h1           |
| 2    | movie     | h2           |
| 3    | was       | h3           |
| 4    | fantastic | h4           |


###Applications of RNN


- Natural Language Processing

      - language modeling

      - text generation

      - sentiment analysis


- Speech Recognition

      Converting speech to text.

      Example:

      Voice assistants.

- Machine Translation

      Translating text between languages.

      Example:

      English → Spanish.

- Time Series Prediction

      Predicting future values from past data.

      Example:

      stock price prediction

      weather forecasting

- Chatbots

      Understanding conversational context.

###Advantages of RNN

| Advantage               | Description                   |
| ----------------------- | ----------------------------- |
| Handles sequential data | Maintains order of inputs     |
| Context awareness       | Uses past information         |
| Useful for NLP          | Processes sentences naturally |


###Limitations of RNN

| Limitation          | Description                           |
| ------------------- | ------------------------------------- |
| Vanishing gradients | Difficult to train long sequences     |
| Slow training       | Sequential computation                |
| Memory limitations  | Cannot capture very long dependencies |


###Problems with RNN


1. Vanishing Gradient Problem

- During training, gradients may become very small.

- This causes the model to forget long-term dependencies.

        Example:

        In a long sentence, earlier words may be forgotten.

2. Exploding Gradient Problem

        Gradients become very large, causing unstable training.

3. Difficulty with Long Sequences

        Standard RNNs struggle to remember information from far earlier in a sequence.

### Advanced RNN Models

- To overcome RNN limitations, improved architectures were developed.

    - LSTM (Long Short-Term Memory)

          Designed to remember long-term dependencies.

    - GRU (Gated Recurrent Unit)

          A simplified version of LSTM.


- Modern NLP systems often use transformer models such as:

          BERT

          GPT


In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [ ]:
sentences = [
"I love this movie",
"This film is amazing",
"I really liked this film",
"This movie is fantastic",

"I hate this movie",
"This film is terrible",
"I did not like this movie",
"This movie is boring"
]

labels = [1,1,1,1,0,0,0,0]

In [ ]:
tokenizer = Tokenizer(num_words=1000)

tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

[[3, 6, 1, 2], [1, 5, 4, 7], [3, 8, 9, 1, 5], [1, 2, 4, 10], [3, 11, 1, 2], [1, 5, 4, 12], [3, 13, 14, 15, 1, 2], [1, 2, 4, 16]]


In [ ]:
#Padding
#Sentences have different lengths, Neural networks require equal length sequences.

padded_sequences = pad_sequences(sequences, maxlen=5)

print(padded_sequences)

[[ 0  3  6  1  2]
 [ 0  1  5  4  7]
 [ 3  8  9  1  5]
 [ 0  1  2  4 10]
 [ 0  3 11  1  2]
 [ 0  1  5  4 12]
 [13 14 15  1  2]
 [ 0  1  2  4 16]]


In [ ]:
model = Sequential()

model.add(Embedding(input_dim=1000, output_dim=16, input_length=5))

model.add(SimpleRNN(32))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()




/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

| Layer     | Purpose                      |
| --------- | ---------------------------- |
| Embedding | Convert word index to vector |
| RNN       | Learn sequence patterns      |
| Dense     | Output prediction            |


In [ ]:
model.fit(
    padded_sequences,
    np.array(labels),
    epochs=20
)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.6958
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6873
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6830
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.6788
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6250 - loss: 0.6745
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.6702
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.6658
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.6613
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6250 - loss: 0.6566
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6250 - loss: 0.6518
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7500 - loss: 0.6468
Epo

In [ ]:
test_sentence = ["I love this film"]

seq = tokenizer.texts_to_sequences(test_sentence)

padded = pad_sequences(seq, maxlen=5)

prediction = model.predict(padded)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 446ms/step
[[0.6033251]]
